

headers = {
    "UniqueItems": ['index', 'version', 'enabled', 'ladder', 'rarity', 'nolimit', 'lvl', 'lvl req', 'code', '*type', '*uber', 'carry1', 'cost mult', 'cost add', 'chrtransform', 'invtransform', 'flippyfile', 'invfile', 'dropsound', 'dropsfxframe', 'usesound', 'prop1', 'par1', 'min1', 'max1', 'prop2', 'par2', 'min2', 'max2', 'prop3', 'par3', 'min3', 'max3', 'prop4', 'par4', 'min4', 'max4', 'prop5', 'par5', 'min5', 'max5', 'prop6', 'par6', 'min6', 'max6', 'prop7', 'par7', 'min7', 'max7', 'prop8', 'par8', 'min8', 'max8', 'prop9', 'par9', 'min9', 'max9', 'prop10', 'par10', 'min10', 'max10', 'prop11', 'par11', 'min11', 'max11', 'prop12', 'par12', 'min12', 'max12', '*eol'],
    "SetItems": ['index', 'set', 'item', '*item', 'rarity', 'lvl', 'lvl req', 'chrtransform', 'invtransform', 'invfile', 'flippyfile', 'dropsound', 'dropsfxframe', 'usesound', 'cost mult', 'cost add', 'add func', 'prop1', 'par1', 'min1', 'max1', 'prop2', 'par2', 'min2', 'max2', 'prop3', 'par3', 'min3', 'max3', 'prop4', 'par4', 'min4', 'max4', 'prop5', 'par5', 'min5', 'max5', 'prop6', 'par6', 'min6', 'max6', 'prop7', 'par7', 'min7', 'max7', 'prop8', 'par8', 'min8', 'max8', 'prop9', 'par9', 'min9', 'max9', 'aprop1a', 'apar1a', 'amin1a', 'amax1a', 'aprop1b', 'apar1b', 'amin1b', 'amax1b', 'aprop2a', 'apar2a', 'amin2a', 'amax2a', 'aprop2b', 'apar2b', 'amin2b', 'amax2b', 'aprop3a', 'apar3a', 'amin3a', 'amax3a', 'aprop3b', 'apar3b', 'amin3b', 'amax3b', 'aprop4a', 'apar4a', 'amin4a', 'amax4a', 'aprop4b', 'apar4b', 'amin4b', 'amax4b', 'aprop5a', 'apar5a', 'amin5a', 'amax5a', 'aprop5b', 'apar5b', 'amin5b', 'amax5b', '*eol'],
    "Sets": ['index', 'name', 'version', 'level', 'PCode2a', 'PParam2a', 'PMin2a', 'PMax2a', 'PCode2b', 'PParam2b', 'PMin2b', 'PMax2b', 'PCode3a', 'PParam3a', 'PMin3a', 'PMax3a', 'PCode3b', 'PParam3b', 'PMin3b', 'PMax3b', 'PCode4a', 'PParam4a', 'PMin4a', 'PMax4a', 'PCode4b', 'PParam4b', 'PMin4b', 'PMax4b', 'PCode5a', 'PParam5a', 'PMin5a', 'PMax5a', 'PCode5b', 'PParam5b', 'PMin5b', 'PMax5b', 'FCode1', 'FParam1', 'FMin1', 'FMax1', 'FCode2', 'FParam2', 'FMin2', 'FMax2', 'FCode3', 'FParam3', 'FMin3', 'FMax3', 'FCode4', 'FParam4', 'FMin4', 'FMax4', 'FCode5', 'FParam5', 'FMin5', 'FMax5', 'FCode6', 'FParam6', 'FMin6', 'FMax6', 'FCode7', 'FParam7', 'FMin7', 'FMax7', 'FCode8', 'FParam8', 'FMin8', 'FMax8', '*eol'],
    "Runes": ['Name', 'Rune Name', 'complete', 'server', 'itype1', 'itype2', 'itype3', 'itype4', 'itype5', 'itype6', 'etype1', 'etype2', 'etype3', '*runes', 'Rune1', 'Rune2', 'Rune3', 'Rune4', 'Rune5', 'Rune6', 'T1Code1', 'T1Param1', 'T1Min1', 'T1Max1', 'T1Code2', 'T1Param2', 'T1Min2', 'T1Max2', 'T1Code3', 'T1Param3', 'T1Min3', 'T1Max3', 'T1Code4', 'T1Param4', 'T1Min4', 'T1Max4', 'T1Code5', 'T1Param5', 'T1Min5', 'T1Max5', 'T1Code6', 'T1Param6', 'T1Min6', 'T1Max6', 'T1Code7', 'T1Param7', 'T1Min7', 'T1Max7', 'eol'],
    "Gems": ['name', 'letter', 'transform', 'code', 'nummods', 'weaponMod1Code', 'weaponMod1Param', 'weaponMod1Min', 'weaponMod1Max', 'weaponMod2Code', 'weaponMod2Param', 'weaponMod2Min', 'weaponMod2Max', 'weaponMod3Code', 'weaponMod3Param', 'weaponMod3Min', 'weaponMod3Max', 'helmMod1Code', 'helmMod1Param', 'helmMod1Min', 'helmMod1Max', 'helmMod2Code', 'helmMod2Param', 'helmMod2Min', 'helmMod2Max', 'helmMod3Code', 'helmMod3Param', 'helmMod3Min', 'helmMod3Max', 'shieldMod1Code', 'shieldMod1Param', 'shieldMod1Min', 'shieldMod1Max', 'shieldMod2Code', 'shieldMod2Param', 'shieldMod2Min', 'shieldMod2Max', 'shieldMod3Code', 'shieldMod3Param', 'shieldMod3Min', 'shieldMod3Max'],
    "MagicPrefix": ['Name', 'version', 'spawnable', 'rare', 'level', 'maxlevel', 'levelreq', 'classspecific', 'class', 'classlevelreq', 'frequency', 'group', 'mod1code', 'mod1param', 'mod1min', 'mod1max', 'mod2code', 'mod2param', 'mod2min', 'mod2max', 'mod3code', 'mod3param', 'mod3min', 'mod3max', 'transform', 'transformcolor', 'itype1', 'itype2', 'itype3', 'itype4', 'itype5', 'itype6', 'itype7', 'etype1', 'etype2', 'etype3', 'etype4', 'etype5', 'divide', 'multiply', 'add'],
    "MagicSuffix": ['Name', 'version', 'spawnable', 'rare', 'level', 'maxlevel', 'levelreq', 'classspecific', 'class', 'classlevelreq', 'frequency', 'group', 'mod1code', 'mod1param', 'mod1min', 'mod1max', 'mod2code', 'mod2param', 'mod2min', 'mod2max', 'mod3code', 'mod3param', 'mod3min', 'mod3max', 'transform', 'transformcolor', 'itype1', 'itype2', 'itype3', 'itype4', 'itype5', 'itype6', 'itype7', 'etype1', 'etype2', 'etype3', 'divide', 'multiply', 'add'],
}
header_maps = {key: {col: idx for idx, col in enumerate(header)} for key, header in headers.items()}


